runtime: python311
service: model-service
entrypoint: uvicorn main:app --host 0.0.0.0 --port $PORT
instance_class: F2

service_account: threat-detection-436007@appspot.gserviceaccount.com

handlers:
- url: /static
  static_dir: static